name: Windows RDP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup User
      run: |
        net user runneradmin Password123!
        net localgroup administrators runneradmin /add

    - name: Enable RDP
      run: |
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip

    - name: Start Tunnel
      run: |
        .\ngrok.exe tcp 3389
