name: Windows-RDP-Tailscale-AutoRestart

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:

    - name: Create User
      run: |
        net user codehub "Codehub1!" /add
        net localgroup administrators codehub /add

    - name: Enable Remote Desktop
      run: |
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Install Tailscale
      run: |
        choco install tailscale -y

    - name: Start Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey $env:TAILSCALE_KEY
      env:
        TAILSCALE_KEY: ${{ secrets.TAILSCALE_KEY }}

    - name: Show Tailscale IP
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" ip -4

    - name: Keep Runner Alive
      run: |
        Start-Sleep -Seconds 21000

    - name: Restart Workflow
      run: |
        curl -X POST `
        -H "Accept: application/vnd.github+json" `
        -H "Authorization: Bearer $env:GITHUB_TOKEN" `
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/rdp.yml/dispatches `
        -d '{"ref":"main"}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
