name: Windows-RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Create User
      run: |
        net user gostdtgamer "31Mar2010!" /add
        net localgroup administrators gostdtgamer /add

    - name: Enable RDP
      run: |
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Download ngrok
      run: |
        curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -o ngrok.zip

    - name: Extract ngrok
      run: |
        tar -xf ngrok.zip

    - name: Start ngrok tunnel
      run: |
        ./ngrok.exe tcp 3389
